apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-cd-demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argo-cd-demo-app
  template:
    metadata:
      labels:
        app: argo-cd-demo-app
    spec:
      containers:
        - name: argo-cd-demo-app
          image: gussf/argo-cd-demo-app
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9000
