apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: gus-demo

images:
- name: argo-cd-demo-app
  newName: gussf/argo-cd-demo-app
  newTag: 4a62973a15be499f3d1c2077e15c80f8ebab7d36
