apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: default

images:
- name: argo-cd-demo-app
  newName: gussf/argo-cd-demo-app
  newTag: ca90c451b42212801414e148c30aab5a7f5030a8
