apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml

namespace: default

images:
  - name: gussf/argo-cd-demo-app
    newTag: 31a446e281a75b2a678a5cdee807e354ec88e2e2
