apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml

namespace: argo-cd-demo-app

images:
  - name: argo-cd-demo-app
    newName: gussf/argo-cd-demo-app
    newTag: v1
