name: cd
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: publish-image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Build and push docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: gussf
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: gussf/argo-cd-demo-app
          tags: ${{ github.sha }}, latest

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize_version: v3.6.1

      - name: update k8s
        run: |
          cd k8s
          kustomize edit set image argo-cd-demo-app=gussf/argo-cd-demo-app:${{ github.sha }}
          cat kustomization.yaml
      - name: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "CD Deploy Action"
          git commit -am "Changing image tag in deployment.yaml to ${{ github.sha }}"
      - name: push
        uses: ad-m/github-push-action@master
