name: ci
on:
  push:
    branches: ["**"]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go build ./...
      - run: go test -v ./...
